sync package metadata
vcpkg/vcpkg.github.io pull request #106
Opened 2023-03-17 16:29 UTC by Sreenivas-Kalluru

sync package metadata daily from Microsoft/vcpkg github repository.

2023-03-17 16:37 UTC, Sreenivas-Kalluru commented
@ras0219  I have performed sync package metadata manually and it generated updated content in output.json and stars.json files. I have validated the star information of the updated packages and it is looking good. Could you please review and merge the changes.
I will create github actions to run the scripts/rebuild.sh daily once these pull request files are looks good.
Thank you.

2023-03-23 20:54 UTC, ras0219-msft requested changes
This only looks like a star update and not a full package update.

For example, the current version of abseil looks to be `20230125.0` but in output.json I see `20211102.1`.

To fully update the package index, you need to change the SHA in rebuild.sh to point at the latest vcpkg commit (right now: 53296052a4ab2036149dc9dc37c5671d0ea486b4).

To get the latest commit, you can use `git rev-parse`:
```
PS C:\src\vcpkg> git fetch https://github.com/microsoft/vcpkg master
From https://github.com/microsoft/vcpkg
 * branch                master     -> FETCH_HEAD
PS C:\src\vcpkg> git rev-parse FETCH_HEAD
53296052a4ab2036149dc9dc37c5671d0ea486b4
```

2023-03-28 15:43 UTC, Sreenivas-Kalluru commented
@ras0219-msft  Could you please review the updated pull request

2023-03-28 15:54 UTC, ras0219-msft requested changes
This should also commit the new rebuild.sh so we can reproduce the results.

2023-03-30 12:59 UTC, closed without merging