capture latest commit dynamically in workflow
vcpkg/vcpkg.github.io pull request #108
Opened 2023-04-12 14:00 UTC by Sreenivas-Kalluru

capture the latest commit dynamically in the workflow to sync package metadata information.

2023-04-12 14:01 UTC, Sreenivas-Kalluru reviewed
@ras0219-msft  Could you please review it

2023-04-19 16:03 UTC, ras0219-msft requested changes

2023-04-19 16:03 UTC, ras0219-msft commented on scripts/rebuild.sh
>  cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")"
We can get the GITHUB_TOKEN from the pipeline itself:
```yaml
- bash: rebuild.sh
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```


https://dev.to/github/the-githubtoken-in-github-actions-how-it-works-change-permissions-customizations-3cgp
https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/

2023-05-15 09:41 UTC, closed without merging

2023-05-15 09:42 UTC, Sreenivas-Kalluru commented
link to #110